[package]
name = "team_queue_bot"
version = "0.1.0"
edition = "2021"

[lib]

[[bin]]
name = "fightbot"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
rand = "0.8"
dotenv = "0.15"
async-trait = "0.1.88"
poise = "0.6"
uuid = { version = "1.17.0", features = ["v4"] }
tracing = "0.1"
tracing-subscriber = "0.3"
